### PR TITLE
Tasks Free

### PR DESCRIPTION
**Pull request by dewral**
Simple task module with task points made by @rookgaard
Edited a little by @tofame
Enjoy!

https://i.imgur.com/q6xTZHS.png

### CODE REVIEW

**Comment by dewral** [comment]
> Hello I was trying but I have this error in server 1.5 \data\scripts\taskSystem.lua
> 
> ```
> Lua Script Error: [CreatureScript Interface]
> data/creaturescripts/scripts/extendedopcode.lua:onExtendedOpcode
> ...\1.5\8XX\data\scripts\taskSystem.lua:286: attempt to call method 'sendExtendedJSONOpcode' (a nil value)
> stack traceback:
>         [C]: in function 'sendExtendedJSONOpcode'
>         ...\1.5\8XX\data\scripts\taskSystem.lua:286: in function 'sendData'
>         ...\1.5\8XX\data\scripts\taskSystem.lua:120: in function 'onAction'
>         data/creaturescripts/scripts/extendedopcode.lua:11: in function <data/creaturescripts/scripts/extendedopcode.lua:3>
> ```

Added json file for lib/core in your engine :)

**Comment by Erza** [comment]
> > Hello I was trying but I have this error in server 1.5 \data\scripts\taskSystem.lua
> > ```
> > Lua Script Error: [CreatureScript Interface]
> > data/creaturescripts/scripts/extendedopcode.lua:onExtendedOpcode
> > ...\1.5\8XX\data\scripts\taskSystem.lua:286: attempt to call method 'sendExtendedJSONOpcode' (a nil value)
> > stack traceback:
> >         [C]: in function 'sendExtendedJSONOpcode'
> >         ...\1.5\8XX\data\scripts\taskSystem.lua:286: in function 'sendData'
> >         ...\1.5\8XX\data\scripts\taskSystem.lua:120: in function 'onAction'
> >         data/creaturescripts/scripts/extendedopcode.lua:11: in function <data/creaturescripts/scripts/extendedopcode.lua:3>
> > ```
> 
> Added json file for lib/core in your engine :)

That did nothing to fix his issue, he's missing the `sendExtendedJSONOpcode` Lua function

**Comment by dewral** [comment]
> > > Hello I was trying but I have this error in server 1.5 \data\scripts\taskSystem.lua
> > > ```
> > > Lua Script Error: [CreatureScript Interface]
> > > data/creaturescripts/scripts/extendedopcode.lua:onExtendedOpcode
> > > ...\1.5\8XX\data\scripts\taskSystem.lua:286: attempt to call method 'sendExtendedJSONOpcode' (a nil value)
> > > stack traceback:
> > >         [C]: in function 'sendExtendedJSONOpcode'
> > >         ...\1.5\8XX\data\scripts\taskSystem.lua:286: in function 'sendData'
> > >         ...\1.5\8XX\data\scripts\taskSystem.lua:120: in function 'onAction'
> > >         data/creaturescripts/scripts/extendedopcode.lua:11: in function <data/creaturescripts/scripts/extendedopcode.lua:3>
> > > ```
> > 
> > 
> > Added json file for lib/core in your engine :)
> 
> That did nothing to fix his issue, he's missing the `sendExtendedJSONOpcode` Lua function

Yeah sorry, but this file was needed anyway. Didn't use that system for some time.
Now it should be good.

**Comment by kokekanon** [comment]
works, thanks

**Pull request closed without merging**
